### ISSUE TITLE
Improve training set simu and RF analysis pipeline graphical interface

### ISSUE THREAD

**Issue by gdurif** [diyabc/diyabcGUI#130]
TODO

Create sub-tabs for sidebar menu `dynamic_tabs` containing

- [x] project setup and administration
- [x] training set simulation
- [x] random forest analysis

**Comment by gdurif** [comment]
Available in version 1.1.2+
